import "./globals.css";
import { DialogContainer, DialogProvider } from "@api/context/DialogContext";
import Footer from "@shared/Footer";
import Header from "@shared/Header";
import RobotoFont from "@ui/RobotoFont";
import type { Metadata } from "next";
import React from "react";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`${RobotoFont.className} antialiased`}>
                <DialogProvider>
                    <Header />
                    <main>{children}</main>
                    <DialogContainer />
                    <Footer />
                </DialogProvider>
            </body>
        </html>
    );
}
