import type { Metadata } from "next";
import "./globals.css";
import Header from "@shared/Header";
import Footer from "@shared/Footer";
import RobotoFont from "@ui/RobotoFont";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="ru">
            <body className={`${RobotoFont.className} antialiased`}>
                <Header />
                <main>{children}</main>
                <Footer />
            </body>
        </html>
    );
}
